### ISSUE TITLE
Add logic if there are too many arguments

### ISSUE THREAD

**Issue by digitalghost-dev** [digitalghost-dev/pl-cli#30]
If there are too many arguments, `if len(os.Args) > 2`, show the help message, print an error message and exit the program.

**Comment by rudransh61** [comment]
He can i work on this issue and project

**Comment by rudransh61** [comment]
Is there is any file to explain this code base?

**Comment by digitalghost-dev** [comment]
@rudransh61 hey, thanks for the interest in contributing. As of right now, this is just a solo project for me to learn Go. Maybe once I get this to a `v1.0.0`, I can bring on other people.
